version: '3'
services:
  web:
    image: ${WEB_IMAGE}
    container_name: ${PROJECT}_web
    restart: always
    build:
      context: ..
      dockerfile: docker/${TYPE}/Dockerfile
    ports:
    - ${WEB_PORT}:3000
    depends_on:
    - postgres
    - redis
    networks:
      rails:
    volumes:
    - log:/app/log
    - challenge:/app/public/challenge
    - acme:/app/acme
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: ${REDIS_URL}
      DATABASE_ADAPTER: ${DATABASE_ADAPTER}
      DATABASE_URL: ${DATABASE_URL}
      FONTAWESOME_NPM_AUTH_TOKEN: ${FONTAWESOME_NPM_AUTH_TOKEN}
      SKIP_TEST_DATABASE: 'true'
  sidekiq:
    image: ${WEB_IMAGE}
    container_name: ${PROJECT}_sidekiq
    restart: 'no'
    build:
      context: ..
      dockerfile: docker/${TYPE}/Dockerfile
    depends_on:
    - web
    networks:
      rails:
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: ${REDIS_URL}
      REDIS_PROVIDER: REDIS_URL
      DATABASE_ADAPTER: ${DATABASE_ADAPTER}
      DATABASE_URL: ${DATABASE_URL}
    entrypoint: bundle exec sidekiq -v
networks:
  rails:
volumes:
  challenge:
  log:
  acme:
