version: '3'
services:
  postgres:
    image: postgres:14
    container_name: ${PROJECT}_postgres
    restart: always
    privileged: true
    ports:
      - target: 5432
        published: 5430
        mode: host
    volumes:
    - ~/.persistence/postgres/${PROJECT}:/opt/postgresql/data
    environment:
      PGDATA: /opt/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6.2-alpine
    container_name: ${PROJECT}_redis
    restart: always
