version: '3'
services:
  node_web:
    image: node_web
    container_name: node_web
    restart: always
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    ports:
    - 4000:4000
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: ${REDIS_URL}
      DATABASE_ADAPTER: ${DATABASE_ADAPTER}
      DATABASE_URL: ${DATABASE_URL}
      SKIP_TEST_DATABASE: 'true'
