version: '3'
services:
  postgres:
    image: postgres:13-alpine
    container_name: ${PROJECT}_postgres
    restart: always
    volumes:
      - ~/.persistence/postgres/${PROJECT}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6.2.5-alpine
    container_name: ${PROJECT}_redis
    restart: always
  nginx:
    image: nginx:1.21-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_HOST: work.design
      NGINX_ROOT: /app/public
    volumes:
      - .persistence/templates:/etc/nginx/templates
      - ~/.persistence/nginx/conf.d:/etc/nginx/conf.d
      - ~/.persistence/nginx/ssl:/etc/nginx/ssl
      - ~/.persistence/nginx/log:/var/log/nginx
