version: '3'
services:
  js:
    image: ${WEB_IMAGE-app}
    container_name: ${PROJECT}_js
    restart: always
    stdin_open: true
    depends_on:
      - web
    volumes:
      - ../app:/app/app
    networks:
      rails:
    entrypoint: yarn run build --watch
  css:
    image: ${WEB_IMAGE-app}
    container_name: ${PROJECT}_css
    restart: 'no'
    depends_on:
      - web
    volumes:
      - ../app:/app/app
    networks:
      rails:
    entrypoint: yarn run build:css --watch
networks:
  rails:
