version: '3'
services:
  postgres:
    image: postgres:14-alpine
    container_name: ${PROJECT}_postgres
    restart: always
    volumes:
    - ~/.persistence/postgres/${PROJECT}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6.2-alpine
    container_name: ${PROJECT}_redis
    restart: always
