version: '3'
services:
  web:
    image: ${WEB_IMAGE-app}
    container_name: ${PROJECT}_web
    restart: always
    build:
      context: ..
      dockerfile: docker/${TYPE}/Dockerfile
    ports:
      - ${WEB_PORT-3000}:3000
    depends_on:
      - postgres
      - redis
    networks:
      rails:
    volumes:
      - ../app:/app/app
    environment:
      RAILS_ENV: ${RAILS_ENV-development}
      REDIS_URL: ${REDIS_URL-redis://redis:6379}
      DATABASE_ADAPTER: ${DATABASE_ADAPTER-postgresql}
      DATABASE_URL: ${DATABASE_URL-postgres://postgres:postgres@postgres/dummy_development}
      SKIP_TEST_DATABASE: 'true'
    entrypoint: bin/rails s -b 0.0.0.0
  job:
    image: ${WEB_IMAGE-app}
    container_name: ${PROJECT}_job
    restart: 'no'
    depends_on:
      - web
    networks:
      rails:
    environment:
      RAILS_ENV: ${RAILS_ENV-development}
      REDIS_URL: ${REDIS_URL-redis://redis:6379}
      DATABASE_ADAPTER: ${DATABASE_ADAPTER-postgresql}
      DATABASE_URL: ${DATABASE_URL-postgres://postgres:postgres@postgres/dummy_development}
      SKIP_TEST_DATABASE: 'true'
    entrypoint: bundle exec good_job start
  js:
    image: ${WEB_IMAGE-app}
    container_name: ${PROJECT}_js
    restart: 'no'
    depends_on:
      - web
    networks:
      rails:
    entrypoint: yarn run build --watch
  css:
    image: ${WEB_IMAGE-app}
    container_name: ${PROJECT}_css
    restart: 'no'
    depends_on:
      - web
    networks:
      rails:
    entrypoint: yarn run build:css --watch
networks:
  rails:
