version: '3'
services:
  nginx:
    image: nginx:1.21-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_ROOT: /app/public
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/conf.d
    volumes:
      - ../.persistence/templates:/etc/nginx/templates
      - ../.persistence/conf.d:/etc/nginx/conf.d
      - ../.persistence/ssl:/etc/nginx/ssl
      - ../.persistence/log:/var/log/nginx
