version: '3'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ../.persistence/db/${PROJECT}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6.2.5-alpine
    restart: always
  web:
    image: ${WEB_IMAGE}
    restart: always
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    ports:
      - ${WEB_PORT}:3000
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: redis://redis:6379
      DATABASE_ADAPTER: ${DATABASE_ADAPTER}
      DATABASE_URL: ${DATABASE_URL}
      SKIP_TEST_DATABASE: 'true'
  sidekiq:
    image: ${WEB_IMAGE}
    restart: always
    depends_on:
      - web
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
    entrypoint: bundle exec sidekiq -r test/dummy
